# Copyright 2024-2026 the original author or authors.
# Licensed under the Apache License, Version 2.0.
#
# Build with `npm run build` in frontend before creating this image.
FROM nginx:1.25.1

COPY frontend/dist /usr/share/nginx/html
COPY deploy/queryweaver/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
